language: node_js
node_js:
  - "12.4"
before_script:
  - npm install
deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app:
    master: staging-project-432
    production: production-project-432

